apiVersion: v1
kind: DeploymentConfig
metadata:
  name: omar-avro-app
  namespace: omar-dev
  selfLink: /oapi/v1/namespaces/omar-dev/deploymentconfigs/omar-avro-app
  uid: dcb57ad5-82c2-11e7-ba3b-0e704fd9c8b2
  resourceVersion: '8864460'
  generation: 200
  creationTimestamp: '2017-08-16T20:38:29Z'
  labels:
    app: omar-openshift
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - omar-avro-app
        from:
          kind: ImageStreamTag
          namespace: o2
          name: 'omar-avro-app:latest'
        lastTriggeredImage: >-
          172.30.181.173:5000/o2/omar-avro-app@sha256:0c1d452533396598662a2a9e56562634d52c191ca303fdded7f28a0ea1c55f2f
  replicas: 1
  test: false
  selector:
    app: omar-openshift
    deploymentconfig: omar-avro-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: omar-openshift
        deploymentconfig: omar-avro-app
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      volumes:
        - name: volume-avro
          persistentVolumeClaim:
            claimName: ossim-data-dev-pvc
      containers:
        - name: omar-avro-app
          image: >-
            172.30.181.173:5000/o2/omar-avro-app@sha256:0c1d452533396598662a2a9e56562634d52c191ca303fdded7f28a0ea1c55f2f
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: SPRING_CLOUD_CONFIG_LABEL
              value: master
          resources:
            limits:
              memory: 4Gi
          volumeMounts:
            - name: volume-avro
              mountPath: /data
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
status:
  latestVersion: 186
  observedGeneration: 200
  replicas: 1
  updatedReplicas: 1
  availableReplicas: 1
  unavailableReplicas: 0
  details:
    message: image change
    causes:
      - type: ImageChange
        imageTrigger:
          from:
            kind: ImageStreamTag
            namespace: o2
            name: 'omar-avro-app:latest'
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2017-10-31T18:15:52Z'
      lastTransitionTime: '2017-10-31T18:15:52Z'
      message: Deployment config has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2017-11-30T12:37:08Z'
      lastTransitionTime: '2017-11-30T12:37:05Z'
      reason: NewReplicationControllerAvailable
      message: replication controller "omar-avro-app-186" successfully rolled out
  readyReplicas: 1
