---
logging:
  config: classpath:logback.groovy

omar:
  avro:
    # The a post to the stager fails, this is the number of miliseconds to wait before trying again.
    attemptDelay: 5000
    # Is the date field in the JSON Avro Record.
    # This field is optional and is used as a way to encode the "directory" for storing the image.
    # If this is not given then the directory suffix will be the path of the "sourceUriField"
    dateField: "observationDateTime"
    # Is the format of the date field.
    # If you leave this blank "" then it will default to parsing an ISO8601 date.
    # Typically left blank.
    dateFieldFormat: "yyyyMMddHHmmss"
    destination:
      # Referes to the type we wish to specify and use.
      # The values can be "stdout" or "post".
      # If the value 'stdout' is used it will just do a println of the message.
      # If the type is "post" then it will post the message to the service definition for the endPoint and the Field.
      type: "post"
      post:
        # If the destination type is "post" then this field needs to be specified to identify the location of the addRaster endpoint.
        # Typically you will be connecting this to a stager-app endpoint which will have a relative path of dataManager/addRaster.
        # The example URL was taken from the ossim-vagrant repo definitions.
        # This will need to be modified for your environment.
        addRasterEndPoint: http://omar-stager-app:8080/omar-stager/dataManager/addRaster
        # If the destination type is "post" then this field is needed to define the post variable used for the filename.
        # By default this field should be left as "filename".
        # It will add the filename value to the addRasterEndPointParams.
        addRasterEndPointField: "filename"
        # This is used as the post parameters to the URL given by the value "addRasterEndPoint".
        # We support modifying the default action being passed and you can specify "background", "buildHistograms", "buildOverviews" flags.
        # The "background" tells the stager to perform the staging as a background process.
        # If this flag is false it will do the staging inline to the endpoint call.
        # You can also specify the parameters "overviewCompressionType" which can be of values "NONE","JPEG","PACKBITS", or "DEFLATE" and also the paramter "overviewType" where the value can be "ossim_tiff_box", "ossim_tiff_nearest", or "ossim_kakadu_nitf_j2k".
        addRasterEndPointParams:
          background: "false"
          buildHistograms: "true"
          buildOverviews: "true"
          overviewCompressionType: "NONE"
          overviewType: "ossim_tiff_box"
          filename: ""
    # This is the download specifications
    download:
      # This is the directory prefix where the file will be downloaded.
      # For example, if we have the "sourceUriField" given as http://[path]/[to]/[image]/foo.tif and the date field content has for a value of 20090215011010 with a dateField format the directory structure will be \<yyyy>/\<mm>/\<dd>/\<hh> where "*yyyy" is a 4 character year and the "mm" is the two character month and the "dd" is the two character day and the "hh" is a two character hour.
      # If the datefield is not specified then we use the path in the URI as a suffix to the local directory defined in the "directory" field above: /data/s3/[path]/[to]/[image]/foo.tif
      directory: "/data/s3"
      # If you do not want the standard HTTP connect to be used in java then you can pass a shell command: ex. `wget -O <destination> <source>` we use where the "source" and "*destination" are replaced internally with the proper values.
      command: "wget --no-check-certificate -O <destination> <source>"
    # Is the image Id field used to identify the image
    imageIdField: "imageId"
    # Allows one to specify a path separated by "." to the submessage to where all the image information resides.
    # For example, if you pass a Message wrapped within the SNS notification it will be a subfield of the SNS message.
    # This allows one to specify a path to the message to be handled.
    jsonSubFieldPath: "Message"
    metadata:
      # Add metadata url.  Just so we can null it out this will have to be
      # set on environments that support it
      # You should just have to add the url:
      # http://omar-avro-metadata-app:8080/omar-avro-metadata/avroMetadata/add
      addMetadataEndPoint: ""
    # If a post to the stager fails, this is how many times it will trtry.
    nAttempts: 10
    # The source URI field name in the JSON Avro record.
    sourceUriField: "uRL"

# Set the context path for the application
#server:
#  contextPath: /omar-avro

# Set the http protocols that swagger is allowed to use
swagger:
  schemes:
    - HTTPS
    - HTTP

---
grails:
    cors:
      enabled: true
    resources:
        pattern: '/**'
    profile: web
    codegen:
        defaultPackage: omar.avro
    spring:
        transactionManagement:
            proxies: false
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
  enabled: true
  health:
    enabled: true
  actuator:
    sensitive: false
  beans:
    sensitive: false
  metrics:
    sensitive: false
  configprops:
    sensitive: false
  trace:
    sensitive: false
  mappings:
    sensitive: false
  env:
    sensitive: false
---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password: ''

environments:
    development:
        dataSource:
            dbCreate: create-drop
            url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    test:
        dataSource:
            dbCreate: update
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    production:
        dataSource:
            dbCreate: update
            url: jdbc:h2:./prodDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
